baseURL       = "https://www.firmeingenieria.com/"
languageCode  = "es-CO"
title         = "FIRME INGENIERÍA"
theme         = "roxo-hugo"
summarylength = 25
publishDir = "docs"

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Inicio"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "¿Quiénes somos?"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Portafolio"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Contacto"
    url     = "contact"
    weight  = 4

# Site Params
[params]
  logo = "images/firme/logo.png"
  #logo_footer = "images/logo-footer.png"
  logo_footer = "images/firme/logo-footer.jpg"
  favicon_icon = "images/firme/favicon.ico"
  favicon_shortcut_icon = "images/firme/favicon.png"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/USAg2Jl"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "Nombre"
    placeholder_last_name         = "Apellido"
    placeholder_email             = "Correo electrónico"
    # placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "Mensaje"
    send_message                  = "Enviar mensaje"

    # [[params.contactForm.projectType]]
    #   value = "gd"
    #   title  = "Graphics Design"
    # [[params.contactForm.projectType]]
    #   value = "wd"
    #   title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Contacto"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/firme-background.jpg"
    heading               = "Soluciones en Ingeniería Civil y SST"
    tagline               = "FIRME INGENIERÍA S.A.S"
    primary_button        = "Portafolio"
    primary_button_url    = "portfolio"
    secondary_button      = "Contáctanos"
    secondary_button_url  = "contact"

  [params.blog]
    read_more             = "read more"

  [params.portfolio]
    enable    = true
    title     = "PROYECTOS RECIENTES"
    # subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."
    view_project = "view project"
    more_works = "MORE WORKS"
    scroll_down = "desplazarse hacia abajo"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "OFRECEMOS LAS MEJORES SOLUCIONES"
    primary_button      = "Portafolio"
    primary_button_url  = "portfolio"
    secondary_button    = "Contáctanos"
    secondary_button_url = "contact"

  [params.footer]
    params.footer.qr_print = false
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Información de contacto"
      address = "Pasto, Nariño, Colombia"
      phone   = "300-XXX-XXXX"
      email   = "info@firmeingenieria.com"
      # Footer Sitemap
      # [params.footer.sitemap]
      #   title   = "Sitemap"
      #   [[params.footer.sitemap.link]]
      #     name = "About Company"
      #     url  = "about"
      #   [[params.footer.sitemap.link]]
      #     name = "Projects"
      #     url  = "portfolio"
      #   [[params.footer.sitemap.link]]
      #     name = "Blog"
      #     url  = "blog"
      #   [[params.footer.sitemap.link]]
      #     name = "Contact"
      #     url  = "contact"
      # Footer Social Media
      # [params.footer.social]
      #   title   = "Social Media"
      #   [[params.footer.social.link]]
      #     name = "Medium"
      #     url  = "#"
      #   [[params.footer.social.link]]
      #     name = "Behance"
      #     url  = "#"
      #   [[params.footer.social.link]]
      #     name = "Dribbble"
      #     url  = "#"
      #   [[params.footer.social.link]]
      #     name = "Instagram"
      #     url  = "#"
      # Footer Service
      # [params.footer.service]
      #   title       = "We help brands:"
      #   description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"
      [params.footer.back_to_top]
        description = "Volver arriba"
